### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by rfarouni** [rdevon/cortex_old#12]
Is the code compatible with Python 2 and 3? I tried adding the following lines to the beginning of the files, but that didn't help

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
```

**Comment by rdevon** [comment]
It should be compatible with Python 2.7

On September 4, 2016 at 3:06:10 PM, Rick Farouni (notifications@github.com) wrote:

Is the code compatible with Python 2 and 3? I tried adding the following lines to the beginning of the files, but that didn't help

from **future** import absolute_import
from **future** import division
from **future** import print_function
