### ISSUE TITLE
Generated AOD.yaml file is missing the .nii extension for field anat_file

### ISSUE THREAD

**Issue by hirocode** [rdevon/cortex_old#5]
When running:
python setup.py install --user

I entered 'Yes'  to download the neuro-imaging data.

The AOD.yaml file that gets generated has the field:
anat_file:[data dir]/ch2better_whitebg_aligned2EPI_V4
This causes an error when running the cortex-rbm-olin-demo.

I changed the field to include the .nii extension:
anat_file:[data dir]/ch2better_whitebg_aligned2EPI_V4.nii

This fixed the problem.

**Comment by rdevon** [comment]
OK! Should be fixed now:
https://github.com/rdevon/cortex/commit/bcd6a0bfc3775231ab7929e95af9ffa81cc9431e

Thanks!
